openapi: 3.0.4
info:
  title: my api
  description: api description
  version: 0.1.9
servers:
  - url: localhost:8080
    description: lokales testen
  - url: https://micedric.dpdns.org
    description: prod server
paths:
  /users:
    get:
      summary: get all users
      description: hallsjdflsajdlöfjsdljfljdf
      responses:
        "200":
          description: all good
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "403":
          description: forbidden content
    post:
      summary: dinge
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
  /locations:
    get:
      summary: get all locations
      description: hasljddddddddddddddddsdljfljdf
      responses:
        "200":
          description: all goooooooood
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404":
          description: not foound
