openapi: 3.0.4
info:
  title: my api
  description: api description
  version: 0.1.9
servers:
  - url: localhost:8080
    description: lokales testen
  - url: https://micedric.dpdns.org
    description: prod server
paths:
  /users:
    get:
      summary: get all users
      descritpion: hallsjdflsajdlöfjsdljfljdf
      responses:
        "200":
          description: all good
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
